server/api/config/routes.rb
Rails.application.routes.draw do
  resources :volatilities
  resources :stock_options
  get 'tradefinder_app/index'

  resources :stocks
  # get 'welcome/index'

  root 'tradefinder_app#index'

  get 'ivr', to: 'ivr#ivr'

  match '*any' => 'application#options', :via => [:options]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

server/api/app/models/stock.rb
class Stock < ApplicationRecord
end

server/api/app/controllers/stocks_controller.rb
require "#{Rails.root}/lib/ameritrade_helper"

class StocksController < ApplicationController
  include AmeritradeHelper

  before_action :set_stock, only: [:show, :edit, :update, :destroy]

  # GET /stocks
  # GET /stocks.json
  def index
    headers['Last-Modified'] = Time.now.httpdate
    session_id = nil

    if !params[:symbols].nil?
      syms = params[:symbols].split(",")
      @stocks = params[:latest] ? [] : Stock.where(symbol: syms)

      login_response = AmeritradeHelper.login(params)
      puts "*** login response #{login_response}"
      unless login_response.nil?
        session_id = login_response[:session_id]
        login_date = login_response[:login_date]
      end

      if !session_id.nil?
        syms.each do |sym|
          new_stocks = AmeritradeHelper.get_stock_symbol(sym, !params[:historic].nil?, params, session)
          @stocks = @stocks + new_stocks unless new_stocks.nil? || !new_stocks.length
        end
      else
        puts "*** session id is nil"
      end

    else
        @stocks = Stock.all
    end

    response = {
        :meta => {
            :session_id => session_id,
            :login_date => login_date
        },
        :data => {
            # :stocks => @stocks.sort_by &:date
            # :stocks => @stocks.order(:date)
            :stocks => @stocks
        }
    }

    respond_to do |format|
      format.html
      format.json { render json: response }
    end
  end

  # GET /stocks/1
  # GET /stocks/1.json
  def show
  end

  # GET /stocks/new
  # def new
  #   if params[:symbols].nil?
  #     @message = 'Symbols not specified'
  #     return
  #   end
  #
  #   @stock = AmeritradeHelper.get_stock_symbol(params[:symbol])
  # end

  # GET /stocks/1/edit
  def edit
  end

  # POST /stocks
  # POST /stocks.json
  # def create
  #   @stock = Stock.new(stock_params)
  #
  #   respond_to do |format|
  #     if @stock.save
  #       format.html { redirect_to @stock, notice: 'Stock was successfully created.' }
  #       format.json { render :show, status: :created, location: @stock }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @stock.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /stocks/1
  # PATCH/PUT /stocks/1.json
  # def update
  #   respond_to do |format|
  #     if @stock.update(stock_params)
  #       format.html { redirect_to @stock, notice: 'Stock was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @stock }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @stock.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /stocks/1
  # DELETE /stocks/1.json
  # def destroy
  #   @stock.destroy
  #   respond_to do |format|
  #     format.html { redirect_to stocks_url, notice: 'Stock was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stock_params
      params.fetch(:stock, {})
    end

end

server/api/app/helpers/stocks_helper.rb
module StocksHelper
end

server/api/app/views/stocks/_form.html.erb
<%= form_for(stock) do |f| %>
  <% if stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
      <% stock.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

server/api/app/views/stocks/edit.html.erb
<h1>Editing Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Show', @stock %> |
<%= link_to 'Back', stocks_path %>

server/api/app/views/stocks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stocks</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stocks.each do |stock| %>
      <tr>
        <td><%= link_to 'Show', stock %></td>
        <td><%= link_to 'Edit', edit_stock_path(stock) %></td>
        <td><%= link_to 'Destroy', stock, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stock', new_stock_path %>

server/api/app/views/stocks/new.html.erb
<h1>New Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Back', stocks_path %>

server/api/app/views/stocks/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_stock_path(@stock) %> |
<%= link_to 'Back', stocks_path %>