server/api/config/routes.rb
Rails.application.routes.draw do
  resources :volatilities
  resources :stock_options
  get 'tradefinder_app/index'

  resources :stocks
  # get 'welcome/index'

  root 'tradefinder_app#index'

  get 'ivr', to: 'ivr#ivr'

  match '*any' => 'application#options', :via => [:options]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

server/api/app/models/volatility.rb
class Volatility < ApplicationRecord
end

server/api/app/controllers/volatilities_controller.rb
require "#{Rails.root}/lib/ameritrade_helper"

class VolatilitiesController < ApplicationController
  before_action :set_volatility, only: [:show, :edit, :update, :destroy]

  # GET /volatilities
  # GET /volatilities.json
  def index
    headers['Last-Modified'] = Time.now.httpdate
    session_id = nil
    response = {}

    if !params[:symbols].nil?
      syms = params[:symbols].split(",")

      login_response = AmeritradeHelper.login(params)
      puts "*** login response #{login_response}"
      unless login_response.nil?
        session_id = login_response[:session_id]
        login_date = login_response[:login_date]
      end

      if !session_id.nil?
        syms.each do |sym|
          AmeritradeHelper.load_volatility(sym, params, session)
        end
      else
        puts "*** session id is nil"
      end

      vols = []
      syms.each do |sym|
        vols << AmeritradeHelper.calculate_ivr(sym)
      end

      response = {
          :meta => {
              :session_id => session_id,
              :login_date => login_date
          },
          :data => {
              :volatility => vols
          }
      }
    end

    respond_to do |format|
      format.html
      format.json { render json: response }
    end


    # @volatilities = Volatility.all
  end

  # GET /volatilities/1
  # GET /volatilities/1.json
  def show
  end

  # GET /volatilities/new
  def new
    @volatility = Volatility.new
  end

  # GET /volatilities/1/edit
  def edit
  end

  # POST /volatilities
  # POST /volatilities.json
  def create
    @volatility = Volatility.new(volatility_params)

    respond_to do |format|
      if @volatility.save
        format.html { redirect_to @volatility, notice: 'Volatility was successfully created.' }
        format.json { render :show, status: :created, location: @volatility }
      else
        format.html { render :new }
        format.json { render json: @volatility.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /volatilities/1
  # PATCH/PUT /volatilities/1.json
  def update
    respond_to do |format|
      if @volatility.update(volatility_params)
        format.html { redirect_to @volatility, notice: 'Volatility was successfully updated.' }
        format.json { render :show, status: :ok, location: @volatility }
      else
        format.html { render :edit }
        format.json { render json: @volatility.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /volatilities/1
  # DELETE /volatilities/1.json
  def destroy
    @volatility.destroy
    respond_to do |format|
      format.html { redirect_to volatilities_url, notice: 'Volatility was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_volatility
      @volatility = Volatility.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def volatility_params
      params.require(:volatility).permit(:symbol, :vol, :date)
    end
end

server/api/app/helpers/volatilities_helper.rb
module VolatilitiesHelper
end

server/api/app/views/volatilities/_form.html.erb
<%= form_for(volatility) do |f| %>
  <% if volatility.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(volatility.errors.count, "error") %> prohibited this volatility from being saved:</h2>

      <ul>
      <% volatility.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :symbol %>
    <%= f.text_field :symbol %>
  </div>

  <div class="field">
    <%= f.label :vol %>
    <%= f.text_field :vol %>
  </div>

  <div class="field">
    <%= f.label :date %>
    <%= f.text_field :date %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

server/api/app/views/volatilities/edit.html.erb
<h1>Editing Volatility</h1>

<%= render 'form', volatility: @volatility %>

<%= link_to 'Show', @volatility %> |
<%= link_to 'Back', volatilities_path %>

server/api/app/views/volatilities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Volatilities</h1>

<table>
  <thead>
    <tr>
      <th>Symbol</th>
      <th>Vol</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @volatilities.each do |volatility| %>
      <tr>
        <td><%= volatility.symbol %></td>
        <td><%= volatility.vol %></td>
        <td><%= volatility.date %></td>
        <td><%= link_to 'Show', volatility %></td>
        <td><%= link_to 'Edit', edit_volatility_path(volatility) %></td>
        <td><%= link_to 'Destroy', volatility, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Volatility', new_volatility_path %>

server/api/app/views/volatilities/new.html.erb
<h1>New Volatility</h1>

<%= render 'form', volatility: @volatility %>

<%= link_to 'Back', volatilities_path %>

server/api/app/views/volatilities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Symbol:</strong>
  <%= @volatility.symbol %>
</p>

<p>
  <strong>Vol:</strong>
  <%= @volatility.vol %>
</p>

<p>
  <strong>Date:</strong>
  <%= @volatility.date %>
</p>

<%= link_to 'Edit', edit_volatility_path(@volatility) %> |
<%= link_to 'Back', volatilities_path %>