server/api/config/routes.rb
Rails.application.routes.draw do
  resources :volatilities
  resources :stock_options
  get 'tradefinder_app/index'

  resources :stocks
  # get 'welcome/index'

  root 'tradefinder_app#index'

  get 'ivr', to: 'ivr#ivr'

  match '*any' => 'application#options', :via => [:options]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

server/api/app/models/stock_option.rb
class StockOption < ApplicationRecord
end

server/api/app/controllers/stock_options_controller.rb
require "#{Rails.root}/lib/ameritrade_helper"

class StockOptionsController < ApplicationController
  include AmeritradeHelper

  before_action :set_stock_option, only: [:show, :edit, :update, :destroy]

  # GET /stock_options
  # GET /stock_options.json
  def index
    headers['Last-Modified'] = Time.now.httpdate
    session_id = nil

    if !params[:symbols].nil?
      syms = params[:symbols].split(",")
      # @stock_options = StockOption.where(symbol: syms)
      @stock_options = []

      login_response = AmeritradeHelper.login(params)
      puts "*** login response #{login_response}"
      unless login_response.nil?
        session_id = login_response[:session_id]
        login_date = login_response[:login_date]
      end

      if !session_id.nil?
        syms.each do |sym|
          # AmeritradeHelper.delete_stock_options(sym)
          new_stock_options = AmeritradeHelper.get_stock_option_symbol(sym, !params[:historic].nil?, params[:minDaysExp], params[:maxDaysExp])
          @stock_options = @stock_options + new_stock_options unless new_stock_options.nil? || !new_stock_options.length
        end
      else
        puts "*** session id is nil"
      end

    else
      @stock_options = StockOption.all
    end

    response = {
        :meta => {
            :session_id => session_id,
            :login_date => login_date
        },
        :data => {
            :stock_options => @stock_options
        }
    }

    respond_to do |format|
      format.html
      format.json { render json: response }
    end

    # @stock_options = StockOption.all
  end

  # GET /stock_options/1
  # GET /stock_options/1.json
  def show
  end

  # GET /stock_options/new
  def new
    @stock_option = StockOption.new
  end

  # GET /stock_options/1/edit
  def edit
  end

  # POST /stock_options
  # POST /stock_options.json
  def create
    @stock_option = StockOption.new(stock_option_params)

    respond_to do |format|
      if @stock_option.save
        format.html { redirect_to @stock_option, notice: 'Stock option was successfully created.' }
        format.json { render :show, status: :created, location: @stock_option }
      else
        format.html { render :new }
        format.json { render json: @stock_option.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stock_options/1
  # PATCH/PUT /stock_options/1.json
  def update
    respond_to do |format|
      if @stock_option.update(stock_option_params)
        format.html { redirect_to @stock_option, notice: 'Stock option was successfully updated.' }
        format.json { render :show, status: :ok, location: @stock_option }
      else
        format.html { render :edit }
        format.json { render json: @stock_option.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stock_options/1
  # DELETE /stock_options/1.json
  def destroy
    @stock_option.destroy
    respond_to do |format|
      format.html { redirect_to stock_options_url, notice: 'Stock option was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock_option
      @stock_option = StockOption.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stock_option_params
      params.require(:stock_option).permit(:symbol, :description, :strike, :call, :mark, :last, :bid, :ask, :theoPrice, :openInterest, :volume, :iv, :percentFromMarket, :probOTM, :delta, :gamma, :theta, :vega, :daysToExpiration, :expiration)
    end
end

server/api/app/helpers/stock_options_helper.rb
module StockOptionsHelper
end

server/api/app/views/stock_options/_form.html.erb
<%= form_for(stock_option) do |f| %>
  <% if stock_option.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stock_option.errors.count, "error") %> prohibited this stock_option from being saved:</h2>

      <ul>
      <% stock_option.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

server/api/app/views/stock_options/edit.html.erb
<h1>Editing Stock Option</h1>

<%= render 'form', stock_option: @stock_option %>

<%= link_to 'Show', @stock_option %> |
<%= link_to 'Back', stock_options_path %>

server/api/app/views/stock_options/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stock Options</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stock_options.each do |stock_option| %>
      <tr>
        <td><%= link_to 'Show', stock_option %></td>
        <td><%= link_to 'Edit', edit_stock_option_path(stock_option) %></td>
        <td><%= link_to 'Destroy', stock_option, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stock Option', new_stock_option_path %>

server/api/app/views/stock_options/new.html.erb
<h1>New Stock Option</h1>

<%= render 'form', stock_option: @stock_option %>

<%= link_to 'Back', stock_options_path %>

server/api/app/views/stock_options/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_stock_option_path(@stock_option) %> |
<%= link_to 'Back', stock_options_path %>